# Generated by Django 5.0.3 on 2024-04-01 01:55

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    Model = apps.get_model('app_cultivo', 'Cultivo')
    Model.objects.create(
        foto = "https://mambodelivery.vtexassets.com/arquivos/ids/155551/abobora-moranga-cortada-1-unidade.jpg?v=637883038388470000", 
        nome = "Abóbora (moranga)", 
        processo = "Para iniciar o cultivo, prepare pequenos berços no solo, com aproximadamente 2 cm de profundidade, e insira de 2 a 3 sementes em cada um. Cubra as sementes gentilmente com terra. Alternativamente, você pode plantar as sementes em recipientes como vasos pequenos, saquinhos plásticos ou copinhos de papel, com dimensões de 10 cm de altura por 5 cm de diâmetro. Quando as mudas estiverem com 3 folhas desenvolvidas, realize o transplante para o local definitivo. Época e Regiões Ideais para o Plantio: O plantio pode ser realizado durante todo o ano, de preferência em regiões onde as temperaturas oscilem entre 15°C e 25°C, com invernos amenos e disponibilidade adequada de água para irrigação, pois a planta é sensível a geadas. A floração e a produtividade da cultura são favorecidas em dias com menor exposição solar. Início de Colheita: 90-120 dias após o plantio.",
        nome_cientifico = "Cucurbita moschata Duch; C. spp"
    )
    Model.objects.create(
        foto = "https://cdn.awsli.com.br/600x1000/1982/1982052/produto/174027508/53c931b15d.jpg", 
        nome = "Alface", 
        processo = "Dependendo da temperatura local, as sementes podem ser plantadas em diferentes locais. Em climas mais amenos, recomenda-se o plantio em hortas, sementeiras, módulos e outros recipientes, a menos de 1 cm de profundidade. Posteriormente, as mudas podem ser transplantadas para o local definitivo. Em regiões de clima quente, é aconselhável realizar o plantio em viveiros. Nesse caso, o transplante para o local definitivo deve ocorrer quando as mudas apresentarem de 4 a 6 folhas crescidas, de preferência em dias nublados, chuvosos ou no fim da tarde, com uma boa irrigação. O espaçamento entre as plantas varia de 20 a 35 cm para cultivos menores e de 30 a 35 cm para cultivos maiores. Além disso, é possível cultivar sem vasos e jardineiras, e até mesmo em sistemas hidropônicos. Época e Regiões Ideais para Plantio: O plantio pode ser realizado durante todo o ano, dependendo da variedade da planta. Existem variedades adequadas para climas quentes e outras mais adaptadas a climas frios. Início de Colheita: 60-80 dias após o plantio no inverno e 50-70 dias após o plantio no verão.",
        nome_cientifico = ": Lactuca sativaL."
    )
    Model.objects.create(
        foto = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRNsUFBiMONJxEGuFdbjkyX-c1x2lz9X8OjLS0cH1Er6mQRo57T", 
        nome = "Agrião", 
        processo = "Para um plantio bem-sucedido em local definitivo, é essencial garantir um solo úmido, preferencialmente com uma camada de água, pois a falta de umidade pode diminuir a taxa de germinação das sementes. As sementes podem ser inicialmente plantadas em sementeiras e, posteriormente, transplantadas quando as mudas atingirem de 4 a 6 folhas desenvolvidas. Outra opção viável é retirar ramos de aproximadamente 15 cm de plantas adultas ou de maços disponíveis no comércio. Esses ramos, quando mergulhados em água, enraízam facilmente. As pontas e folhas podem ser colhidas antes do plantio das ramas. O espaçamento adequado entre os plantios é de 20 a 30 cm. Quanto à época e regiões ideais para o plantio, recomenda-se realizar o cultivo em regiões com temperaturas entre 15°C e 25°C, preferencialmente durante o outono e inverno. Em regiões de verões pouco quentes, o plantio pode ser realizado durante todo o ano. Início de Colheita: 60-70 dias após o plantio.",
        nome_cientifico = "Nasturtium officinale W.T. Aiton"
    )
    Model.objects.create(
        foto = "https://conteudo.imguol.com.br/blogs/218/files/2019/02/iStock-517895450.jpg", 
        nome = "Alho", 
        processo = "O plantio pode ser realizado tanto por sementes quanto pelos bulbos do fruto. No caso dos bulbos, é recomendado separá-los por tamanho e garantir que estejam em bom estado. Eles devem ser plantados no local definitivo a uma profundidade de 3 a 5 cm, ou até 8 cm em regiões mais frias. Alternativamente, podem ser inicialmente semeados em bandejas ou sementeiras e depois transplantados quando brotarem. Ao plantar, posicione a parte mais fina do bulbo voltada para cima, mantendo um espaçamento de 25 a 30 cm entre as linhas de plantio e de 10 cm entre cada planta. Em áreas menores, sem linhas de plantio, o espaçamento recomendado é de 15 a 18 cm entre plantas. Também é possível cultivá-los em vasos e jardineiras. Para regiões de clima quente, os bulbos devem ser armazenados refrigerados, entre 0°C e 10°C, por um período de 1 ou 2 meses antes do plantio. Quanto à época e regiões ideais para o plantio, as melhores cabeças são colhidas de plantações realizadas no outono, e em regiões frias também no início da primavera. Cultivos tardios exigem um mínimo de 13 horas de luz por dia e podem ser plantados no extremo sul do Brasil ou no centro-sul, mas apenas após a vernalização dos bulbos. Início de Colheita: 150-180 dias após plantio.",
        nome_cientifico = "Allium sativum L."
    )
    Model.objects.create(
        foto = "https://scfoods.fbitsstatic.net/img/p/batata-doce-org-500g-71993/258642.jpg?w=800&h=800&v=no-change&qs=ignore", 
        nome = "Batata doce", 
        processo = "A batata-doce pode ser plantada a partir de ramas retiradas de plantas adultas, diretamente das próprias batatas-doces ou por meio de sementes. Em regiões tropicais, é mais comum utilizar ramas de plantas adultas com 8 a 10 entrenós, sendo que cada entrenó apresenta uma folha, resultando em 8 a 10 folhas desenvolvidas por rama. As ramas devem ser enterradas até a metade e firmadas com terra em solo úmido. Alguns preferem estimular a brotação das batatas-doces em recipientes cobertos de água antes do plantio. Para aumentar a quantidade de mudas, aguarde que as ramas cresçam até atingir entre 30 a 50 cm antes de cortá-las na base e plantá-las no local definitivo. O plantio por meio de sementes é feito em pequenos vasos, saquinhos de plástico com 35 cm de diâmetro e profundidade, ou em copos de papel jornal com 10 cm de altura por 5 cm de diâmetro. O transplante das mudas deve ser realizado quando atingirem entre 10 a 15 cm de altura. Quanto à época e regiões ideais para o plantio, a batata-doce desenvolve-se bem em regiões de temperaturas elevadas. Ela não tolera o frio, o qual reduz sua produtividade e não suporta geadas. Em regiões de baixa altitude, com invernos suaves, é possível realizar o plantio ao longo de todo o ano.",
        nome_cientifico = "Ipomoea batatas L."
    )
    Model.objects.create(
        foto = "https://i0.wp.com/comidadebebe.pt/wp-content/uploads/2022/07/Blog-5-4.jpg?resize=1080%2C675&ssl=1", 
        nome = "Beterraba", 
        processo = "Para plantar beterrabas, é recomendado utilizar os glomérulos de frutos que contêm as sementes, os quais devem ser colocados no local definitivo a uma profundidade de 1 cm, após retirar o excesso de plantas, com as mudas atingindo entre 5 a 10 cm de altura. Se preferir plantar em sementeiras ou outros recipientes, as mudas devem ser transplantadas quando alcançarem 5 cm de altura, após uma germinação que geralmente leva de 1 a 3 semanas. Para os plantios de beterraba oleráceas, o espaçamento entre as linhas deve ser de 30 cm, com 5 a 10 cm entre as plantas. Para as beterrabas açucareiras, recomenda-se um espaçamento de 30 a 60 cm entre as linhas e de 15 a 30 cm entre as plantas. Já para as beterrabas-forrageiras, o espaçamento varia entre 40 e 100 cm entre as linhas e de 15 a 60 cm entre as plantas. Quanto à época e regiões ideais para o plantio, é preferível realizar o plantio em regiões com temperaturas entre 15°C e 25°C. As beterrabas são resistentes ao frio e a geadas, porém não toleram temperaturas e umidade muito elevadas.",
        nome_cientifico = "Beta vulgaris L."
    )
    Model.objects.create(
        foto = "https://cdn.awsli.com.br/600x450/1304/1304130/produto/50539468/b72ece6ecf.jpg", 
        nome = "Beringela", 
        processo = "Para facilitar a germinação, é recomendado deixar as sementes na água por um dia. Alternativamente, se preferir germinar as sementes antes do plantio, o processo pode levar de 1 a 2 semanas. Nesse caso, utilize sementeiras, saquinhos de plástico ou copinhos de papel, e transplante as mudas quando atingirem entre 8 a 10 cm de altura. Ao plantar as sementes, disponha-as na superfície do solo e cubra-as com uma leve camada de terra peneirada ou serragem fina. O espaçamento entre as plantas varia de acordo com o clima local: em regiões mais quentes, é recomendável aumentar o espaçamento, enquanto em climas frios, é possível diminuí-lo. Geralmente, o espaçamento entre as linhas dos plantios varia de 60 cm a 1 m, e entre as plantas, de 50 cm a 1 m. As espécies mais comuns também podem ser cultivadas em vasos grandes, sendo preferíveis as de menor porte. Quanto à época e regiões ideais para o plantio, recomenda-se realizar o cultivo em regiões de clima quente. As plantas são favorecidas pelo calor, especialmente durante a germinação, emergência e formação das mudas. Início de Colheita: 100-120 dias após plantio.",
        nome_cientifico = "Solanum melongena L."
    )
    Model.objects.create(
        foto = "https://static.escolakids.uol.com.br/2019/04/brocolis.jpg", 
        nome = "Bróculis ou couve-brócolos", 
        processo = "Para iniciar o cultivo, plante as sementes diretamente no local definitivo, enterrando-as a uma profundidade de 1 cm no solo. O espaçamento recomendado varia de 60 cm a 1 m entre as linhas de plantio e de 30 cm a 60 cm entre as plantas individuais. Alternativamente, as sementes também podem ser germinadas em sementeiras, vasos pequenos, copinhos de plástico ou jornal. Transplante as mudas quando alcançarem 4 a 6 folhas verdadeiras, preferencialmente no final da tarde e em solo úmido ou em dias nublados. A germinação ocorre em menos de 1 ou 2 semanas. Quanto à época e às regiões ideais para o plantio, existem variedades adaptadas a diferentes climas quentes, permitindo o cultivo em diversas regiões. Início de Colheita: 80-100 dias após plantio.",
        nome_cientifico = "Brassica oleracea L. var. italica Plenck"
    )
    Model.objects.create(
        foto = "https://www.arenaatacado.com.br/on/demandware.static/-/Sites-storefront-catalog-sv/default/dw8f22640e/Produtos/29636-0000000004062-cebola%20kg-flv-1.jpg", 
        nome = "Cebola", 
        processo = "Para iniciar o cultivo, é possível utilizar sementes ou pequenos bulbos produzidos especialmente para esse fim. No caso de bulbos, plante-os diretamente no local definitivo, enterrando-os a uma profundidade de 2 ou 3 cm no solo. Recomenda-se um espaçamento de 25 a 45 cm entre as linhas de plantio e de 10 a 15 cm entre as plantas individuais. Se optar por utilizar sementeiras, o transplante das mudas para o local definitivo deve ocorrer entre 40 e 60 dias após o plantio inicial. O período de germinação das sementes varia de 1 a 2 semanas. Quanto à época e às regiões ideais para o plantio, os bulbos crescem e amadurecem mais rapidamente sob temperaturas altas e com mais de 10 horas de luz diária. No entanto, plantas expostas ao frio podem ser induzidas a florescer, o que pode ser benéfico para produtores de sementes. Início de Colheita: 120-180 dias após plantio.",
        nome_cientifico = "Allium cepa L."
    )
    Model.objects.create(
        foto = "https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia29053/plantar-cebolinha-verde-1-tecnologia-e-treinamento.jpg", 
        nome = "Cebolinha", 
        processo = "A cebolinha pode ser plantada através de sementes ou da divisão de touceiras formadas por plantas adultas. As sementes podem ser semeadas diretamente no local definitivo ou em sementeiras, sendo as mudas transplantadas quando atingem um tamanho adequado. O método de divisão de touceiras consiste em separar cada planta da touceira, garantindo que cada uma tenha folhas bem desenvolvidas, e então plantá-las espaçadamente, mantendo a mesma profundidade em que estavam anteriormente. É importante notar que algumas variedades de cebolinha-verde se propagam vegetativamente, tornando-as inadequadas para o plantio por divisão. No entanto, tanto a cebolinha-verde quanto a cebolinha-francesa podem ser cultivadas em vasos e jardineiras. Quanto à época e às regiões ideais para o plantio, é recomendado para regiões com temperaturas inferiores a 25°C, preferencialmente durante as estações de outono e inverno. Início de Colheita: 80-100 dias após plantio.",
        nome_cientifico = "Allium schoenoprasum L."
    )
    Model.objects.create(
        foto = "https://io.convertiez.com.br/m/trimais/shop/products/images/18/medium/cenoura-260g_18.jpg", 
        nome = "Cenoura", 
        processo = "Para o plantio de cenouras, é essencial que o solo esteja solto e poroso, sem obstáculos que possam impedir o crescimento adequado das raízes, o que ajuda a evitar deformações indesejadas. Um solo bem preparado contribui significativamente para o desenvolvimento saudável das cenouras. O momento ideal para a colheita das cenouras é quando as folhas começam a amarelar e a secar. Isso indica que as raízes atingiram o ponto de maturidade e estão prontas para serem colhidas. É importante estar atento a esse sinal para garantir uma colheita no momento certo, quando as cenouras estão no auge do sabor e da textura. Quanto à época e às regiões ideais para o plantio, uma temperatura entre 20°C e 30°C proporciona uma germinação rápida e uniforme das sementes de cenoura. Para as variedades de cenouras de verão, o plantio em temperaturas mais baixas pode não ser vantajoso, sendo mais útil para produtores de sementes que buscam selecionar variedades adaptadas a diferentes condições climáticas. Início de Colheita: 85-100 dias após plantio.",
        nome_cientifico = "Daucus carota L."
    )
    Model.objects.create(
        foto = "https://t3.ftcdn.net/jpg/05/36/70/08/360_F_536700883_MZGmzYrZEHpKwxXOqhtIIqqcetsy1GQw.jpg", 
        nome = "Chuchu", 
        processo = "O plantio é realizado com o fruto inteiro, o qual é capaz de brotar facilmente. Após a colheita, o fruto deve ser deixado em um local escuro por cerca de 2 semanas. Quando os brotos atingirem uma altura entre 10 a 15 cm, está na hora de realizar o plantio. Basta posicionar o broto sobre a terra ou enterrá-lo parcialmente, evitando assim o risco de apodrecimento. O espaçamento recomendado entre as plantas varia de 5 m a 7 m, embora alguns agricultores optem por espaçamentos mais estreitos, entre 3 m e 4 m. Quanto à época e às regiões ideais para o plantio, a planta prospera sob temperaturas entre 15°C e 25°C, não tolerando temperaturas excessivamente baixas. Calor e chuvas intensas podem causar a queda das flores e aumentar a suscetibilidade a doenças fúngicas. Portanto, é importante manter um equilíbrio adequado entre a temperatura e a umidade para garantir um cultivo saudável. Início de Colheita: 100-120 dias após plantio",
        nome_cientifico = "Sechium edule Sw."
    )
    Model.objects.create(
        foto = "https://acdn.mitiendanube.com/stores/002/955/442/products/coentro-verdao111-500be36d973b1cd38016801984108442-1024-1024.jpg", 
        nome = "Coentro", 
        processo = "As sementes de coentro podem demorar para germinar, sendo útil deixá-las de molho em água por 1 a 3 dias para auxiliar no processo. Além disso, temperaturas em torno de 27°C são favoráveis para o crescimento das plantas. Ao plantar, posicione as sementes no local definitivo a uma profundidade de 1 cm no solo. É importante notar que o coentro não tolera bem o transplante, mas caso necessário, pode ser cultivado inicialmente em copos de papel jornal ou saquinhos de plástico. Ao transplantar as mudas, faça-o com cuidado para não perturbar muito as raízes. Para o cultivo em vasos e jardineiras, escolha recipientes com pelo menos 30 cm de profundidade, devido às raízes longas da planta. Quanto à época e às regiões ideais para o plantio, o coentro é uma cultura que prospera em climas quentes e não tolera baixas temperaturas. Portanto, é preferível cultivá-lo em regiões com clima predominantemente quente para garantir um bom desenvolvimento das plantas. Início de Colheita: 50-60 dias após plantio.",
        nome_cientifico = "Coriandrum sativum L."
    )
    Model.objects.create(
        foto = "https://cafaracruz.com.br/wp-content/uploads/2021/06/couve.jpg", 
        nome = "Couve", 
        processo = "A couve pode ser plantada com sementes ou através de rebentos retirados de plantas adultas, especialmente em algumas variedades. Os rebentos são obtidos a partir de gemas axilares no caule principal, os quais devem ser retirados da base da planta, com pelo menos 20 cm de comprimento. As sementes podem ser semeadas diretamente na horta, em sementeiras ou em outros recipientes. As mudas devem ser transplantadas quando atingirem de 4 a 6 folhas verdadeiras e tiverem pelo menos 10 cm de altura. A germinação das sementes geralmente leva de 1 a 2 semanas. O transplante ideal deve ser realizado em dias nublados, chuvosos ou no final da tarde, seguido imediatamente de irrigação. Plante as sementes a uma profundidade de 1 cm. Quanto ao espaçamento, varia de acordo com as variedades cultivadas, mas geralmente utiliza-se de 50 cm a 1 m entre as linhas de cultivo e de 25 a 50 cm entre as plantas individuais. Além disso, a couve também pode ser cultivada em vasos, os quais devem ter no mínimo 25 cm de diâmetro e altura. Quanto à época e às regiões ideais para o plantio, a couve é típica de outono e inverno, embora tenha certa tolerância ao calor. Dependendo da região, pode ser plantada durante todo o ano, adaptando-se às condições climáticas locais. Início de Colheita: 80-90 dias após plantio.",
        nome_cientifico = "Brassica oleracea L. var. acephalaD.C."
    )
    Model.objects.create(
        foto = "https://http2.mlstatic.com/D_NQ_NP_658333-MLB51718896135_092022-O.webp", 
        nome = "Couve-chinesa", 
        processo = "A planta pode ser inicialmente cultivada em sementeiras, vasos pequenos ou copinhos de plástico ou jornal, e posteriormente transplantada quando possuir de 4 a 6 folhas desenvolvidas. Recomenda-se realizar o transplante no final da tarde ou em dias nublados, garantindo que o solo esteja bem úmido para facilitar a adaptação das mudas. As sementes também podem ser diretamente semeadas no local definitivo, ou em jardineiras e vasos maiores. O espaçamento entre as plantas varia de acordo com a espécie, mas geralmente situa-se entre 30 a 40 cm. Quanto à época e às regiões ideais para o plantio, a planta prospera melhor sob temperaturas entre 15ºC e 25ºC, embora haja espécies que apresentam tolerância ao calor. Essa faixa de temperatura proporciona condições ideais para o crescimento saudável da planta, garantindo assim um desenvolvimento robusto. Início de Colheita: 60-70 dias após plantio.",
        nome_cientifico = "Brassica pekinensis (Lour.) Rupr."
    )
    Model.objects.create(
        foto = "https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/cenourao/media/uploads/produtos/foto/b57dad07c378580583.png", 
        nome = "Couve-flor", 
        processo = "As sementes podem ser plantadas em sementeiras, vasos ou canteiros. Após a germinação, que geralmente ocorre em 1 ou 2 semanas, as mudas devem ser transplantadas para o local definitivo quando possuírem de 4 a 6 folhas. Plante as sementes a uma profundidade de 1 cm no solo. Também é possível semear as sementes diretamente na horta, ajustando o espaçamento ao retirar o excesso de plantas para alcançar o espaçamento desejado. O espaçamento ideal varia de acordo com a espécie: para variedades de verão, recomenda-se um espaçamento de 45 a 60 cm, enquanto para as de inverno, o espaçamento ideal é entre 50 a 75 cm. Para mini couves-flores, utilize um espaçamento entre plantas de 15 a 40 cm. Quanto à época e às regiões ideais para o plantio, existem espécies adaptadas tanto a climas quentes quanto a temperaturas entre 15ºC e 25ºC. É importante selecionar as variedades adequadas de acordo com as condições climáticas da região de plantio para garantir o sucesso do cultivo. Início de Colheita: 100-110 dias após plantio no inverno e 90-110 dias após plantio no verão.",
        nome_cientifico = "Brassica oleracea var. botritys"
    )
    Model.objects.create(
        foto = "https://global.cdn.magazord.com.br/mondiniplantas/img/2023/02/produto/3042/feijao.jpg?ims=800x800", 
        nome = "Feijão-Vagem", 
        processo = "Plante as sementes diretamente no local definitivo, enterrando-as a uma profundidade de 2 cm a 4 cm no solo. Alternativamente, é possível germinar as sementes previamente, colocando-as em uma bandeja forrada com papel, algodão ou tecido úmido até que as raízes comecem a aparecer. Somente então as sementes devem ser transferidas para o solo. O feijão-de-vagem também pode ser cultivado em vasos e jardineiras, desde que esses recipientes tenham o tamanho adequado para a espécie. Recomenda-se um espaçamento de 40 a 60 cm entre as linhas de plantio e de 7 a 10 cm entre as plantas individuais. Quanto à época e às regiões ideais para o plantio, o feijão-de-vagem não tolera baixas temperaturas e geadas. Ele se desenvolve melhor em temperaturas entre 15°C e 25°C. Em regiões com invernos mais amenos, o plantio pode ser realizado durante todo o ano, aproveitando as condições climáticas favoráveis para o cultivo dessa planta. Início de Colheita: 60-70 dias após plantio.",
        nome_cientifico = "Phaseolus vulgaris L."
    )
    Model.objects.create(
        foto = "https://cdn.awsli.com.br/600x450/4/4552/produto/1387017/d8ec8f3dad.jpg", 
        nome = "Gengibre", 
        processo = "A plantação é realizada com pedaços de rizomas, conhecidos como gomos, com 3 a 5 cm de comprimento, inseridos no local definitivo a uma profundidade de 5 cm no solo. Alternativamente, esses gomos também podem ser inicialmente plantados em canteiros e vasos para serem transplantados após 1 mês, quando as mudas atingirem cerca de 3 cm de altura. O espaçamento recomendado varia de acordo com o método de cultivo: entre 70 a 90 cm entre as linhas de plantio e de 30 a 50 cm entre as plantas individuais. Em lavouras mecanizadas, o espaçamento é maior, com linhas duplas de 1,3 m x 50 cm x 20 ou 30 cm. Além disso, é possível cultivar em vasos grandes, especialmente em áreas domésticas dentro da casa, protegidas dos meses de frio. Quanto à época e às regiões ideais para o plantio, essa planta se desenvolve melhor em climas tropicais e subtropicais. No entanto, é sensível à geada e não tolera temperaturas abaixo de 13°C, o que limita seu cultivo em regiões com invernos rigorosos.Início de Colheita: 240-300 dias após plantio.",
        nome_cientifico = "Zingiber officinale Roscoe"
    )
    Model.objects.create(
        foto = "https://t4.ftcdn.net/jpg/00/17/04/25/360_F_17042504_n9DhlvgAag9hoIMVR5K5qV1loxFMa6MD.jpg", 
        nome = "Jiló", 
        processo = "As sementes podem ser plantadas em canteiros, sementeiras ou em copinhos feitos de papel jornal, com dimensões de 10 cm de altura por 5 ou 6 cm de diâmetro. A germinação ocorre geralmente em 1 ou 2 semanas. Quando as mudas alcançam 6 folhas definitivas, é hora de transplantá-las, com altura de 5 a 10 cm. O espaçamento adequado varia de 100 a 150 cm entre as linhas de plantio e de 60 a 100 cm entre as plantas individuais. Além disso, essa planta também pode ser cultivada em vasos grandes. Quanto à época e às regiões ideais para o plantio, trata-se de uma espécie típica de clima tropical, preferencialmente plantada nos períodos de primavera e verão. Em regiões com invernos mais brandos, é possível realizar o plantio durante todo o ano, aproveitando as condições climáticas favoráveis para o cultivo dessa planta. Início de Colheita: 90-100 dias após plantio.",
        nome_cientifico = "Solanum gilo Raddi"
    )
    Model.objects.create(
        foto = "https://images.tcdn.com.br/img/img_prod/763396/maxixe_311_1_20200320161655.jpg", 
        nome = "Maxixe", 
        processo = "Para o plantio, prepare o local definitivo criando berços de 30 cm de profundidade e 30 cm de diâmetro. A terra retirada deve ser adubada com esterco bem curtido, húmus de minhoca, composto orgânico ou fertilizante mineral natural. Após adubar a terra, recoloque-a nos berços e irrigue bem. Plante 2 ou 3 sementes a uma profundidade de 2 cm. Quando as plantas atingirem 10 cm de altura, realize um desbaste, deixando apenas 1 ou 2 plantas por berço para um melhor desenvolvimento. As sementes também podem ser plantadas em pequenos vasos, sacos para mudas, copos de papel jornal ou outros recipientes adequados. Quando as mudas atingirem 4 ou 5 folhas, devem ser transplantadas para o local definitivo. O espaçamento recomendado é de 2 a 3 m entre as linhas de plantio e de 1 metro entre as plantas individuais. Quanto à época e às regiões ideais para o plantio, trata-se de uma hortaliça de clima tropical, capaz de suportar temperaturas elevadas e chuvas abundantes. Em regiões de altitude, o plantio é recomendado durante a primavera e o verão. Na Região Norte, é importante observar que o excesso de chuvas pode favorecer o surgimento de doenças, sendo necessário um manejo adequado para evitar problemas fitossanitários. Início de Colheita: 60-70 dias após plantio.",
        nome_cientifico = "Cucumis anguria L."
    )
    Model.objects.create(
        foto = "https://revistacampoenegocios.com.br/wp-content/uploads/2020/11/Melancia-01.jpg", 
        nome = "Melancia", 
        processo = "Para o plantio direto no local definitivo, é essencial que as condições climáticas sejam adequadas. Caso contrário, as sementes devem ser inicialmente semeadas em vasos com 10 cm de diâmetro ou em sacos para mudas. Posteriormente, as mudas devem ser transplantadas quando atingirem de 10 a 15 cm de altura. No local definitivo, prepare covas de 30 ou 40 cm de diâmetro e profundidade, adicionando terra previamente adubada. As sementes devem ser semeadas a uma profundidade de 2 a 5 cm, com até 6 sementes por cova. Após a germinação, que pode levar entre 4 e 14 dias, elimine as plantas mais fracas, deixando apenas 2 ou 3 por cova. O espaçamento entre as covas varia de 2 a 3 m, garantindo um desenvolvimento adequado das plantas. Quanto à época e às regiões ideais para o plantio, essa planta requer temperaturas elevadas e não tolera frio nem geadas. É adequada para regiões de baixa altitude, especialmente aquelas com irrigação, como as observadas no Centro-Oeste do Brasil. Além disso, pode ser plantada no outono e inverno, desde que as condições climáticas sejam favoráveis ao seu desenvolvimento. Início de Colheita: 85-90 dias após plantio.",
        nome_cientifico = "Citrullus lanatus (Thunb.) Matsum. & Nakai"
    )
    Model.objects.create(
        foto = "https://apoioentrega.vteximg.com.br/arquivos/ids/521145/95295.jpg?v=638175996044100000", 
        nome = "Milho-verde", 
        processo = "As sementes devem ser plantadas diretamente no local definitivo. O espaçamento recomendado é de 1 m entre as linhas e 20 cm entre as plantas para variedades maiores. Para espécies menores, como algumas variedades de hortaliças, o espaçamento pode ser reduzido para 80 cm entre as linhas e 20 cm entre as plantas. Para cultivo em pequena escala, o espaçamento pode ser ainda menor, com 30 cm entre as linhas e 20 cm entre as plantas. Além disso, é possível plantar em vasos grandes, com cerca de 50 cm de diâmetro. Para esses vasos, pode-se colocar até 3 sementes, formando um triângulo. Em vasos menores, é recomendado plantar apenas 1 ou 2 sementes. Alternativamente, as sementes também podem ser inicialmente plantadas em sementeiras ou copinhos feitos de papel jornal e posteriormente transplantadas quando atingirem de 8 a 10 cm de altura. É importante plantar um mínimo de 4 plantas para facilitar a polinização, sendo ideal colocar 9 plantas. O plantio em formato quadrado, em vez de em linha, também pode contribuir para uma melhor polinização. Evite plantar diferentes espécies próximas umas das outras; mantenha uma distância mínima de 400 m entre espécies diferentes, pois características fenotípicas distintas podem resultar em espigas com grãos de cores variadas. Quanto à época e às regiões ideais para o plantio, essa cultura prospera em regiões de clima quente e fresco. Ela não tolera frio nem geadas, portanto, em regiões com invernos rigorosos, o plantio é recomendado durante todo o ano, aproveitando as condições climáticas favoráveis para o cultivo. Início de Colheita: 80-110 dias após plantio.",
        nome_cientifico = "Zea mays L."
    )
    Model.objects.create(
        foto = "https://files.agro20.com.br/uploads/2019/07/pepino-3.jpg", 
        nome = "Pepino", 
        processo = "Para o cultivo do pepino, plante as sementes diretamente no local definitivo, pois a planta não suporta bem o transplante. As sementes germinam melhor em temperaturas abaixo de 20°C. No entanto, em invernos brandos, é possível semear as sementes em vasos, saquinhos de plástico para mudas ou copos feitos de papel jornal, mantendo-os em locais aquecidos. A germinação ocorre geralmente entre 5 e 15 dias após o plantio, portanto, tenha paciência. Ao plantar as sementes, faça isso a uma profundidade de 2 ou 3 cm. O espaçamento entre as plantas varia conforme o método de cultivo. Para cultivo tutorado, recomenda-se um espaçamento de 60 cm a 1 m entre as linhas e de 45 a 50 cm entre as plantas. Para plantas que crescem rasteiras, como algumas variedades de pepino, o espaçamento é maior, de 2 m entre as linhas e de 75 cm a 1 m entre as plantas. Se o objetivo é produzir pepino para conserva, o espaçamento ideal é de 1 m a 1,2 m entre as linhas e de 20 cm entre as plantas. Além do plantio direto no solo, o pepino também pode ser cultivado em vasos com pelo menos 30 cm de diâmetro e profundidade. No entanto, é importante notar que a maioria das variedades não cresce e produz bem em vasos. Quanto à época e às regiões ideais para o plantio, o pepino prospera em climas quentes, adaptando-se a temperaturas entre 15°C e 25°C. Frio e geadas podem prejudicar seu crescimento, mas em regiões com invernos brandos, o cultivo em estufas pode ser uma opção viável. Início de Colheita: 45-60 dias após plantio.",
        nome_cientifico = "Cucumis sativus L."
    )
    Model.objects.create(
        foto = "https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/cenourao/media/uploads/produtos/foto/f54f6b53037bfile.png", 
        nome = "Pimenta", 
        processo = "Para o cultivo desta planta, é recomendado dar preferência ao uso de sementeiras, copos ou saquinhos de plástico ou papel, embora também seja possível plantá-la diretamente no local definitivo. As sementes devem ser enterradas a uma profundidade de 0,5 cm no solo, ou podem ser colocadas sobre papel mata-borrão ou outro papel absorvente, mantidos sempre úmidos e em local aquecido até a germinação, que ocorre normalmente em 1 ou 2 semanas. Em temperaturas inferiores a 20°C, esse processo pode ser mais lento. O transplante das mudas deve ser realizado quando estas atingirem de 8 a 10 cm de altura. O espaçamento entre as plantas pode variar de 20 cm a 60 cm, enquanto o espaçamento entre as linhas deve ser de 60 cm a 120 cm, dependendo das condições específicas e da variedade cultivada. Além disso, é possível cultivar esta planta em vasos, oferecendo-lhe cuidados adequados. Quanto à época de plantio e regiões ideais, esta planta prefere condições quentes e não tolera baixas temperaturas nem geadas. Assim, é recomendado plantá-la durante os meses mais quentes do ano, especialmente em regiões de baixa altitude. Em locais com invernos amenos, o cultivo pode ser realizado durante todo o ano. Época e regiões para plantio: Exigem calor e não toleram baixas temperaturas nem geadas. Dali que devam cultivar-se nos meses de alta temperatura. Em regiões de baixa altitude, com invernos fracos pode ser plantada o ano inteiro. Início de Colheita: 90-120 dias após plantio.",
        nome_cientifico = "Capsicum frutescens L.; C. baccatum L.; C. chinense Jacq.; C. praetermissum L."
    )
    Model.objects.create(
        foto = "https://www.infoescola.com/wp-content/uploads/2010/08/piment%C3%A3o_270503105.jpg", 
        nome = "Pimentão", 
        processo = "Pode-se optar pelo plantio direto no local definitivo, mas é recomendado realizar o plantio em sementeiras, copos ou saquinhos de plástico ou papel. As sementes devem ser colocadas a uma profundidade de 0,5 cm no solo, e a germinação geralmente ocorre dentro de 1 a 3 semanas. Quando as mudas atingem cerca de 10 cm de altura, é o momento adequado para o transplante. O espaçamento recomendado varia entre 60 a 120 cm entre as linhas e 40 a 60 cm entre as plantas. Além disso, é possível cultivar esta planta em vasos, desde que estes tenham uma profundidade e diâmetro mínimos de 35 cm. Quanto à época e regiões ideais para o plantio, esta planta prospera melhor em temperaturas elevadas ou entre 15° e 25° C. Não tolera temperaturas frias nem geadas. Em regiões onde o inverno é brando, é possível cultivá-la durante todo o ano, aproveitando as condições climáticas favoráveis. Início de Colheita: 100-120 dias após plantio.",
        nome_cientifico = " Capsicum annuum L."
    )
    Model.objects.create(
        foto = "https://www.proativaalimentos.com.br/image/cache/catalog/img_prod/06112018091527000000772131[1]-1000x1000.jpg", 
        nome = "Quiabo", 
        processo = "As sementes desta planta podem ser plantadas diretamente no local definitivo, embora leve mais de 3 semanas para germinar. Uma alternativa para acelerar o processo de germinação é deixá-las em um recipiente com água por 1 dia, o que pode reduzir o tempo de germinação para cerca de 1 semana. Além disso, é possível semear as sementes em pequenos vasos, copos de plástico ou saquinhos, e depois transplantar as mudas para o local definitivo quando atingirem de 10 a 15 cm de altura. Quanto à época e regiões ideais para o plantio, esta planta requer temperaturas altas e não tolera o frio. Portanto, é recomendado plantá-la em regiões e durante períodos do ano onde as temperaturas são mais elevadas, proporcionando as condições ideais para seu desenvolvimento. Início de Colheita: 70-80 dias após plantio.",
        nome_cientifico = "Abelmoschus esculentus (L.) Moench"
    )
    Model.objects.create(
        foto = "https://www.mundoboaforma.com.br/wp-content/uploads/2020/09/beneficios-do-repolho.jpg", 
        nome = "Repolho", 
        processo = "Para o plantio desta planta, as sementes podem ser colocadas diretamente no local definitivo ou em sementeiras. Após a germinação, que normalmente ocorre em menos de 1 semana, as mudas devem ter entre 10 a 15 cm de altura para serem transplantadas. A profundidade de plantio das sementes deve ser de 1 a 2 cm. O espaçamento entre as plantas pode variar de 30 a 60 cm, dependendo da espécie e das condições específicas do cultivo. Quanto à época e regiões ideais para o plantio, esta planta prefere temperaturas moderadas entre 15° e 25° C e pode resistir bem a geadas. No entanto, também existem espécies adaptadas a temperaturas mais altas. Portanto, o momento e o local de plantio devem ser escolhidos levando em consideração as características específicas da planta e as condições climáticas da região. Início de Colheita: 90-110 dias após plantio.",
        nome_cientifico = "Brassica oleracea L. var. capitata"
    )
    Model.objects.create(
        foto = "https://images.tcdn.com.br/img/img_prod/760333/semente_de_rucula_folha_larga_10_gramas_horticeres_1591_1_0e06c4dc700ef4b6e9625aab1026629b.jpg", 
        nome = "Rúcula", 
        processo = "Para o plantio desta planta, as sementes podem ser colocadas diretamente no local definitivo, na superfície do solo ou a uma profundidade não superior a 0,5 cm. A germinação das sementes geralmente ocorre em um período de 4 a 8 dias. Quando as plantas atingirem cerca de 10 cm de altura, podem ser transplantadas, se necessário. O espaçamento entre as linhas pode variar de 15 a 60 cm, enquanto o espaçamento entre as plantas pode variar de 10 a 30 cm, dependendo das características da planta e das condições específicas do cultivo. Quanto à época e regiões ideais para o plantio, esta planta prefere temperaturas moderadas entre 15° e 25° C. Em regiões com invernos fracos, ela pode ser plantada durante todo o ano, proporcionando condições favoráveis para o seu crescimento e desenvolvimento. Início de Colheita: 40-60 dias após plantio.",
        nome_cientifico = "Eruca sativa L."
    )
    Model.objects.create(
        foto = "https://thumbs.web.sapo.io/?W=800&H=0&delay_optim=1&epic=YzIzuII18av68yZ0wU0ipbqSbaXghQwBTI0UBHFHUqQzxiYChKN5Ba/WBMqfBz/e/tRHrNs01rLcJII/vzUxCUVQ98ILpvsvQ1N+jvy1skUFZC0=", 
        nome = "Salsa", 
        processo = "Para esta planta, as sementes podem demorar de 2 a 6 semanas para germinar. Para acelerar esse processo, recomenda-se deixá-las de molho em água morna por 1 dia antes do plantio. Além disso, elas podem ser plantadas em jardineiras e vasos de tamanho adequado, sendo recomendável que os vasos tenham pelo menos 30 cm de profundidade e diâmetro para permitir um bom desenvolvimento das raízes. Quanto à época e às regiões ideais para o plantio, esta planta prefere áreas com temperaturas em torno de 20°C, não muito frias nem muito quentes. Portanto, é importante escolher um período e um local de plantio que proporcionem condições climáticas adequadas para o crescimento saudável da planta. Início de Colheita: 60-70 dias após plantio.",
        nome_cientifico = "Petroselinum crispum (Mill.) Nym."
    )
    Model.objects.create(
        foto = "https://static1.squarespace.com/static/5b8edfa12714e508f756f481/5bb7d929a4222f8b31418ae5/5bbcf80015fcc00ead6882ba/1544815130008/?format=1500w", 
        nome = "Tomate", 
        processo = "Para essa planta, você pode optar por plantar diretamente no local definitivo ou em recipientes como sementeiras, copos ou saquinhos de plástico ou papel, que devem ter cerca de 10 cm de altura e 7 cm de diâmetro. Coloque de 2 a 5 sementes em cada recipiente, a uma profundidade de 1 cm, e após a germinação, resgate apenas 1 ou 2 das plantas mais vigorosas para transplantar. O momento ideal para o transplante é quando as plantas atingirem de 15 cm a 25 cm de altura. Se desejar, você pode enterrar parte do caule ao transplantar para promover o surgimento de mais raízes. O espaçamento entre as plantas varia de acordo com o hábito de crescimento: para as de hábito indeterminado, recomenda-se de 50 cm a 1,6 m entre plantas, enquanto para as de hábito determinado, o espaçamento ideal é de 50 cm a 1 m. Além disso, essas plantas podem ser cultivadas em uma variedade de recipientes, como vasos, jardineiras, cestas suspensas, sacos plásticos com terra e outros. Para espécies anãs, você pode usar vasos pequenos, deixando cerca de 30 cm entre as plantas. Quanto à época e às regiões ideais para o plantio, essas plantas preferem regiões altas, serras e planaltos com clima tropical e subtropical. Elas também podem ser cultivadas em climas temperados, desde que sejam secos e tenham alta incidência de luz solar. No entanto, regiões muito úmidas e quentes podem favorecer o surgimento de doenças, então é importante estar atento a isso durante o cultivo. Início de Colheita: 100-120 dias após plantio.",
        nome_cientifico = "Lycopersicom esculentum Mill."
    )

   
class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cultivo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("foto", models.TextField(max_length=255)),
                ("nome", models.TextField(max_length=255)),
                ("processo", models.TextField(max_length=255)),
                ("nome_cientifico", models.TextField(max_length=255)),
            ],
        ),
        migrations.RunPython(load_initial_data)
    ]
