# Generated by Django 5.0.6 on 2024-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cultivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='foto',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nome_cientifico',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='processo',
            field=models.TextField(max_length=300),
        ),
    ]
