# Generated by Django 5.0.3 on 2024-04-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_atividades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="dt_atividade",
            field=models.DateTimeField(),
        ),
    ]
