# Generated by Django 5.0.2 on 2024-04-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_atividades", "0002_alter_atividade_dt_atividade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atividade",
            old_name="dt_atividade",
            new_name="dt_atividadedb",
        ),
    ]
