# Generated by Django 5.0.2 on 2024-04-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_atividades", "0003_rename_dt_atividade_atividade_dt_atividadedb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="dt_atividadedb",
            field=models.DateField(),
        ),
    ]
