# Generated by Django 5.0.2 on 2024-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_atividades", "0004_alter_atividade_dt_atividadedb"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="usuario_id",
            field=models.CharField(default="admin", max_length=100),
        ),
    ]
