# Generated by Django 5.0.4 on 2024-04-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horta',
            name='descricao',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='horta',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horta.horta')),
            ],
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_plantio', models.DateField()),
                ('ultima_atv', models.DateField(null=True)),
                ('descricao_atv', models.TextField(null=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horta.cultura')),
            ],
        ),
    ]
