# Generated by Django 5.0.4 on 2024-04-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horta', '0002_alter_horta_descricao_alter_horta_nome_cultura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horta',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='descricao_atv',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
