# Generated by Django 5.0.3 on 2024-04-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_horta', '0003_alter_horta_descricao_alter_plantio_descricao_atv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultura',
            old_name='descricao',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='cultura',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cultura',
            old_name='tipo',
            new_name='type',
        ),
    ]
