# Generated by Django 5.0.3 on 2024-05-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='topico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_forum.topico'),
            preserve_default=False,
        ),
    ]
